name: J Kaiser Portfolio
favicon: null
layout_spectrum: 0.16559
typography_spectrum: 0.07897186814807355
title: Jacques Kaiser Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1708'
    - '#655a48'
    - '#bca184'
    - '#fed072'
    - '#fcf5e4'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.41359297558665276
purpose: []
